### PR TITLE
Included crawler service demo

### PR DESCRIPTION
**Pull request by chandrams**

### CODE REVIEW

**Comment by dinogun** [comment]
@chandrams Can you please all of the common code between the various local monitoring demos to one place and not duplicate the code. I dont think we need most of the code that is present in this PR

**Comment by chandrams** [comment]
@dinogun - I have updated the bulk API as per the latest code changes and moved the common code out. Please review.

**Comment by dinogun** [comment]
@chandrams Please update the README.md and add content on the bulk API demo goals. Ideally bulk APIs are going to be more useful to users than the individual APIs as users can get recommendations for individual workloads or groups of them by fiddling with the `filter`. I'd suggest adding enough documentation around this to enable users to tweak the input JSON to achieve whatever they are interested.

Also in a separate PR, we can have additional examples of various bulk input json's that will enable users to get the right kind of recommendations

**Comment by chandrams** [comment]
@dinogun - I have updated the readme for bulk demo, please review.

**Review by dinogun — APPROVED** [review]
LGTM

**Pull request merged**
