### PR TITLE
Add support for AKS

### PR DESCRIPTION
**Pull request by krishvoor**
This PR adds support for AKS [Azure Kubernetes Service]

### CODE REVIEW

**Review by msvinaykumar — APPROVED** [review]
LGTM

**Comment by msvinaykumar** [comment]
@krishvoor can you please resole conflicts . Rest LGTM ..thank you

**Review by chandrams — COMMENTED** [review]
Please resolve the conflicts

**Comment by krishvoor** [comment]
Hi @chandrams @msvinaykumar 👋 - can you ptal?
Conflicts are resolved

**Review by msvinaykumar — APPROVED** [review]
LGTM

**Review by chandrams — APPROVED** [review]

**Comment by chandrams** [comment]
@krishvoor - Were you able to fix the signing?

**Comment by dinogun** [comment]
@krishvoor Thank you for adding AKS support!

**Pull request merged**
