### PR TITLE
Fix bulk changes

### PR DESCRIPTION
**Pull request by kusumachalasani**
Update the bulk demo to fix the issues that were causing the previous version to break.
- No installation of TFB by default 
- Create a log file and redirect the logs.

### CODE REVIEW

**Comment by chandrams** [comment]
@kusumachalasani Has this been tested? can you share the output log

**Comment by kusumachalasani** [comment]
> @kusumachalasani Has this been tested? can you share the output log

In process of creating a cluster and test it. Will update the log once the testing is complete.

**Comment by kusumachalasani** [comment]
Attaching the output log from the bulk demo.
[log.zip](https://github.com/user-attachments/files/17538786/log.zip)

**Comment by chandrams** [comment]
@kusumachalasani - Can we display a message when Kruize is being setup as it takes more than a minute after the initial display of kruize local demo setup.

**Comment by kusumachalasani** [comment]
> @kusumachalasani - Can we display a message when Kruize is being setup as it takes more than a minute after the initial display of kruize local demo setup.

Done.

**Review by chandrams — APPROVED** [review]
LGTM

**Pull request merged**
